### ISSUE TITLE
HTML `</tr>` tags missing

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-docsgen#14] opened 2023-11-16 12:55 UTC
## Describe the bug

As reported by @webbnh [here](https://github.com/arcalot/arcaflow-plugin-pcp/pull/20#discussion_r1387004630):

```
<tr><th>Properties</th><td><details><summary>pmlogger_conf (<code>string</code>)</summary>
                <table><tbody><tr><th>Name:</th><td>pmlogger configuration file</td></tr><tr><th>Description:</th><td>Complete configuration file content for pmlogger as a multi-line string. If no config file is provided, a default one will be generated.</td></tr><tr><th>Required:</th><td>No</td></tr><tr><th>Type:</th><td><code>string</code></td></tbody></table>
```
> Before each `</tbody>` tag there's a missing `</tr>` tag.

**Comment by dustinblack** [comment] 2024-04-17 13:08
I can't find evidence of this problem anymore. All of the recent docs rendering I've looked through seem to have the appropriate `</tr>` tags. I'm going to go ahead and close this one. FYI @webbnh

**Comment by webbnh** [comment] 2024-04-19 17:06
[Here's an example](https://github.com/arcalot/arcaflow-plugin-pcp/blob/9653d35ee42ae55b5abc5ba91e05d24b01c32afd/README.md?plain=1#L88).

About two thirds of the `</tbody>` tags in that file are still following an unclosed `<tr>` tag.  Most of the [good ones](https://github.com/arcalot/arcaflow-plugin-pcp/blob/9653d35ee42ae55b5abc5ba91e05d24b01c32afd/README.md?plain=1#L163-L167) appear to be outer tables, so the problem seems to coming from the innermost nested tables. 

I think it's the last line of each "Properties" table.  (Although, [here's one](https://github.com/arcalot/arcaflow-plugin-pcp/blob/9653d35ee42ae55b5abc5ba91e05d24b01c32afd/README.md?plain=1#L94) that's good for no immediately obvious reason.)  Could it be that the properties list is converted to a table by inserting `</tr><tr>` between the entries and the code simply neglects to append the `</tr>` at the end?

**Comment by webbnh** [comment] 2024-04-19 17:56
I believe the problem is [here](https://github.com/arcalot/arcaflow-docsgen/blob/eb25b1ae4e8f1a8af71b173d6e71af49d78f5d99/templates/markdown/partials/type.md.tpl#L1-L30).  The expansion of the `type` template starts with a `<tr>` but doesn't supply the matching, closing tag.  (I checked the other `partials` templates, and they all seem OK.)

**Closed as completed** 2024-09-03 20:40 UTC
Labels: bug
